[{"errorType":"java.lang.reflect.InvocationTargetException","errorMessage":"Произошла внутренняя ошибка","errorSource":"com._1c.g5.v8.dt.platform.services.ui","stackTrace":"java.lang.reflect.InvocationTargetException\tat com._1c.g5.v8.dt.internal.platform.services.ui.infobases.wizard.InfobaseWizard.createSection(InfobaseWizard.java:467)\tat com._1c.g5.v8.dt.internal.platform.services.ui.infobases.wizard.InfobaseWizard.lambda$3(InfobaseWizard.java:156)\tat org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)\tCaused by: com._1c.g5.v8.dt.platform.services.core.runtimes.execution.RuntimeExecutionException\tat com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.AbstractRuntimeComponentExecutor.executeRuntimeProcessCommand(AbstractRuntimeComponentExecutor.java:348)\tat com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.AbstractRuntimeComponentExecutor.executeRuntimeProcessCommand(AbstractRuntimeComponentExecutor.java:97)\tat com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.ThickClientLauncher.createInfobase(ThickClientLauncher.java:90)\tat com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.lambda$1(DesignerSessionThickClientLauncher.java:211)\tat com._1c.g5.v8.dt.internal.platform.services.core.runtimes.execution.DesignerSessionOperationSupport.execOutOfDesignerSession(DesignerSessionOperationSupport.java:302)\tat com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.execOutOfDesignerSession(DesignerSessionThickClientLauncher.java:863)\tat com._1c.g5.v8.dt.platform.services.core.runtimes.execution.impl.DesignerSessionThickClientLauncher.createInfobase(DesignerSessionThickClientLauncher.java:210)\tat com._1c.g5.v8.dt.internal.platform.services.ui.infobases.wizard.InfobaseWizard.createSection(InfobaseWizard.java:435)\t... 2 more","type":"FormattedErrorEvent","name":"com._1c.g5.v8.dt.platform.services.ui/error","timestamp":1652725342518}]